// First import of the Story Bank from the "Personal Cartography stories" document.
// Rules followed (brief §5): one document ≠ one story; separate events kept separate; only what the source
// actually says is recorded, in Claire's own words wherever possible; gaps become follow-up questions.
// Everything defaults to privacy: 'private'. Numbers after "Cartography #" are the item numbers in the source.
// Personal / family / health items in the document that do not bear on the public thesis were NOT imported;
// they remain in the source document, and Claire can add them if she wants them here.

const SRC = 'Personal Cartography stories (Google Doc / PDF)';
const now = '2026-09-11T12:00:00.000Z';
const S = (o) => ({ kind: 'story', privacy: 'private', territories: [], relatedQuestions: [], possibleQuestions: [], newQuestions: [], followups: [], transcript: [], createdAt: now, updatedAt: now, dismissed: false, source: SRC, ...o });

export const STORIES_SEED = [
  S({
    id: 'S001', kind: 'lead', sourceRef: 'Cartography, opening note ("Downside of competence")',
    title: 'Being told I didn’t look the part',
    period: 'Mid-20s', context: 'In the US, checking in on a team after an acquisition before going to work on another one',
    people: '“a seekio person in the US” (unnamed) who gave the advice',
    happening: 'I was in the US, checking in on a team after an acquisition before going to work on another one. I was mid-20s. “You’re really good but you don’t look the part” a seekio person in the US said. You need to get photos to look professional and be taken seriously.',
    did: 'I went to have photos taken, to try and do the professional thing but it didn’t feel right. I stood through the photo shoot.',
    next: 'I hated the outcome, the energy in the photo and it followed me around for a long time after.',
    thinkNow: 'It taught me that I should have ignored the advice and tune into it more.',
    quotes: '“You’re really good but you don’t look the part.”',
    ideas: 'Downside of competence. Symptoms of competence. Being good enough to continue, even though it’s not right. Couldn’t see a bigger perspective no one else knew about.',
    territories: ['N', 'K', 'B'], relatedQuestions: [14, 17],
    followups: ['Who gave the advice, and what was their role in the acquisition?', 'What was happening at work at that moment — which deal, which team?', 'Why did credibility matter right then?', 'What changed afterwards — did you act differently in the next acquisition?', 'What does the incident reveal now: about advice, about “looking the part”, about competence being enough to keep going?'],
  }),
  S({
    id: 'S002', sourceRef: 'Cartography #1 "Learning to do hard things – the hard way"; #68 "Working on M&A deals"',
    title: 'Learning to do M&A the hard way, as the outsider',
    context: 'M&A in different businesses in the US (and Asia). The source says 10 acquisitions in one place and “14 mergers and acquisitions across the US and Asia” in another.',
    role: 'Working on M&A in different businesses in the US. I was an outsider, learning as I went.',
    happening: 'Some days felt like I’d signed up for a slow walk but someone, somewhere had turned the treadmill up to 15 and I was sprinting for my life. Knowing that if I stopped pounding the floor, I’d become a heap at the end. Battered.',
    difficulty: 'Trying to keep my chin up when seen as the outsider, a person who is a walking red flag of change and turning those relationships around to build connection. This wasn’t helped by the fact I was younger than them and British too. I was seen as an outsider or even the enemy. I often felt out of place and like a fraud, learning on the fly.',
    did: 'I learned to make fast judgement from the outside. My methods were challenged and refined. Learning to speak to anyone and how to navigate hard situation doing all the grotty stuff of leadership. I handled tough situations, including making redundancies, being isolated abroad and helped integrate teams into a new way of working.',
    thinkNow: 'Every deal required empathy, resilience, and the ability to shift perspectives in high-stakes environments which would have taken longer to do any other way.',
    quotes: '“a walking red flag of change”',
    ideas: 'Learning to do difficult M&A/integration work while doing it. Fast judgement from the outside. The outsider as the visible symbol of change.',
    territories: ['B', 'D', 'N', 'F'], relatedQuestions: [5, 15, 55, 45],
    followups: ['This is “M&A experience” as one story — which individual deals sit underneath it? List them, even just by place and year.', 'Which deal was the treadmill-at-15 one?', 'What was the first fast judgement you made from the outside that turned out right? And one that turned out wrong?', 'What did the deal team care about that you didn’t, and vice versa?', 'Is it 10 acquisitions or 14? (The source says both.)'],
  }),
  S({
    id: 'S003', sourceRef: 'Cartography #5 "A young leader managing older people in a foreign land"; #69',
    title: 'A young British leader managing a hostile older US team',
    context: 'USA, managing a group of older people after an acquisition (the source implies the M&A context)',
    happening: 'I was managing a group of older people in the USA and they were hostile towards me. I had two things against me: 1) I was young 2) I was British.',
    difficulty: 'It was a baptism of fire in converting people’s views, in getting them to like me. Back then I cared deeply. Even now, I care more than I let on. As a young leader, I often found myself guiding older, more experienced professionals through restructuring. It made me feel deeply insecure at times, worrying about being replaced or not being taken seriously.',
    did: 'Let people feel. People were angry about my age or experience? They probably have a reason. Let them feel it. And then, when it comes to approaching them: understand where they’re great. Look for it. Instead of looking for reasons to overrule people, look for space where they can be the better of the two of you.',
    thinkNow: 'There’s more than enough room for you both to be great. That’s what you should be aiming for. Over time, I’ve learned that discomfort is part of the process — and leading through it is where real growth happens.',
    quotes: '“I saw a girl with a short black dress and ankle boots and thought ‘she must be the Brit.’” · “Have you seen my new manager, she’s younger than my car.” · “If you can change this department I’ll buy you a Louis Vuitton bag.” · “Wonder what or who she did to get here.”',
    ideas: 'What makes people accept leadership from someone with less experience than them? Letting people feel vs. needing to be liked.',
    territories: ['C', 'N', 'B', 'D'], relatedQuestions: [12, 46, 17],
    followups: ['Which acquisition and which department was this?', 'Who said the Louis Vuitton line — and did the department change? Did you get the bag?', 'Who surprised you by coming round, and what turned it?', 'Was there anyone you never won over? What happened to them?', 'What did “let people feel” cost you at the time?'],
  }),
  S({
    id: 'S004', sourceRef: 'Cartography #6 "Being fired in public at 22"; #41 "What Getting Fired Did to My Career"',
    title: 'Fired two weeks into my first post-uni job',
    period: 'Age 22, first job after university', context: 'Two weeks into the role; the managing director took me to a nearby coffee shop',
    people: 'The managing director',
    happening: 'It was Monday morning and I’d been there two weeks, taken countless interviews to get the job, resigned from my old one. Declined another offer. “Fancy a coffee” he said. I ordered a coffee, he didn’t get one. That was the first sign that something wasn’t right. “It’s not working” came the opener. “We’re letting you go… don’t worry, we’ll pay you to the end of the week, you have a week’s notice.” I kept my eyes focused on his.',
    next: 'I’d spent months preparing for this role, only to be left scrambling, barely able to cover rent and wondering if I’d have to move back in with my parents.',
    thinkNow: 'Jobs are never as secure as they seem, probationary periods are nerve-wracking for a reason, and firing someone can be done better. Since then, I’ve stayed too long at roles, holding onto golden handcuffs like promotions and share deals. I’ve often wondered if I should have left earlier, especially in 2022–2023. Getting fired felt devastating, but it forced me to see the precarious nature of work and the need to take control of my own career.',
    scenes: 'He didn’t order a coffee. Walking up the hill a couple of doors from the office.',
    ideas: 'How being fired shaped a later pattern of staying too long. Security vs. fear.',
    territories: ['R', 'K', 'Q'], relatedQuestions: [47],
    followups: ['Why did they say it wasn’t working — did you ever find out?', 'What specifically would you do differently from him when letting someone go? (Connects to S008.)', 'Which roles did you stay in too long, and what were the golden handcuffs each time?'],
  }),
  S({
    id: 'S005', sourceRef: 'Cartography #7 "Doing an MBA and realising that most of it was rubbish"',
    title: 'Disagreeing with the HR Director teaching redundancy on my MBA',
    context: 'MBA class; I was running a global marketing team at the time', people: 'A HR Director in Germany (the lecturer)',
    happening: '“This isn’t how it would work” I said to him. He was a HR Director in Germany. I was running a global marketing team and I disagreed with his sentiment. But he had the power. I had to sit down and keep quiet.',
    difficulty: 'Injustice that I’d lived this and that the lessons being shared with the class wouldn’t work in practice. That the questions that come from sharp people are less predictable than his demo case studies.',
    thoughtThen: 'When terminating people of jobs that take the food off their table, there are questions, feelings, anger that the people might have. A raw reaction isn’t HR friendly. You can’t tell people how to feel, and when you’re making someone redundant you have no right to try. Truth be told, you’re probably doing it to lower overall headcount to keep your own job. Cutting heads keeps others alive.',
    thinkNow: '“People don’t care if you find it hard news to deliver. It’s not about you, it’s about them. And if you have to do it, all you can do, is do it fairly, clearly, and with as much dignity as you can. Offer to write recommendations and put that in writing for when they’re ready. Because one day they’re not going to hate you this much. One day they’re going to be grateful of that open offer. Offer it and stand by your word.”',
    ideas: 'Accepted advice that did not fit reality. Competent answer wrong for the situation. What a leader owes people when there is no good outcome.',
    territories: ['E', 'G', 'Q', 'F'], relatedQuestions: [50, 56, 58],
    followups: ['Which redundancy had you actually lived through by then — the one that taught you this?', 'Did you ever get to make the case to the class, or did it stay unsaid?', 'Has anyone come back for that recommendation? When?'],
  }),
  S({
    id: 'S006', sourceRef: 'Cartography #9 "Business lessons from nan"',
    title: 'Nan’s books: learning a P&L at the kitchen table',
    period: 'Saturday mornings, around 1998', context: 'Nan ran a school kitchen into her 80s and “did the books” every Saturday', people: 'Nan',
    happening: 'Each piece of paper spread out before her is a menu. Every Saturday, she’d ‘do the books’ while I watched South Park. But soon, her work started to seem more interesting than TV. I’d eavesdrop, curious, and eventually start asking questions: “How does the budget work?” “How much did people pay for lunch?” £2. “What if they went over budget?” Never happened.',
    thinkNow: 'What I didn’t realise back then was that I was learning about something I’d spend my career navigating — a more complex version of ‘Nan’s books.’ Today, it’s called a P&L.',
    scenes: 'Toes squelching through brown carpet; the radio humming; rating menus — roast beef 6/10, fish and chips 7/10, chocolate crisp 10/10.',
    ideas: 'Numbers learned informally, before they had a name. Connects to the later budget stories (S013).',
    territories: ['F'], relatedQuestions: [58],
    followups: ['When did “Nan’s books” first become useful at work — the first budget you owned?'],
  }),
  S({
    id: 'S007', sourceRef: 'Cartography #11 "Culture achieves what rules can’t"',
    title: 'Tennessee: the acquired company that had escaped the group’s rules',
    context: 'Visiting “Tennessee’s best place to work — a title they’d earned nine years running”. They had escaped the rigid rules of their group.',
    happening: 'Offices for everyone, ping pong tables, and fully stocked fridges. What really surprised me was how they approached hiring. A guy from support, who knew nothing about technical roles, was in charge of ensuring new hires were a cultural fit. His job was to protect their vibe, not just fill seats.',
    thoughtThen: 'This was my first real glimpse of what workplace culture could do. It wasn’t about perks or policies — it was about shared values and purpose. I left inspired, knowing culture can achieve what rules never will.',
    ideas: 'What should stay local in an acquired business and what should be centralised. A business that performed because it was allowed to be different from its owner.',
    territories: ['B', 'A'], relatedQuestions: [38, 28, 4],
    followups: ['Was this company part of your group, or one you were about to acquire/integrate?', 'What happened to that culture afterwards — did the group’s rules eventually reach it?', 'Did you argue for leaving it alone? To whom, and what happened?'],
  }),
  S({
    id: 'S008', sourceRef: 'Cartography #31 "Art after firing someone"',
    title: 'Firing someone in Atlanta, then standing in front of a painting',
    context: 'Atlanta, US', people: 'The person I fired; the person she worked for',
    happening: 'I once fired someone in Atlanta. She was nice enough but the person she worked for wasn’t happy with what she was doing and she went awol a lot. I offered her the chance to resign, to make it work on her terms. Instead, she sat in front of me with tears in her eyes saying that I had to let her go. Telling me that if I didn’t let her go, she couldn’t claim unemployment, that I had to fire her.',
    role: 'The person doing the firing — the first time I did it.',
    did: 'I fired her. After that, I couldn’t shake the feeling. I had to get out of there, I had to out move that energy, to get it to move through me and leave and so I headed downtown, on the train line to Atlanta Museum of High Art. I stood in front of a painting, with half its face covered, the other half looking downcast. I stood there for a long time.',
    thoughtThen: 'I felt a poison sweep over me, taking my humanity as it covered each piece of my flesh turning me into a piece of shit. I lumped that feeling around for long enough to know that I couldn’t focus.',
    ideas: 'The person inside the change: the cost of a decision that was “commercially sensible” to someone else. What a leader owes when there is no good outcome — and the employee knowing the system better than the manager (unemployment rules).',
    territories: ['D', 'E', 'R', 'F'], relatedQuestions: [43, 50, 48],
    followups: ['Who decided she had to go — you, or the person she worked for? Did you agree?', 'What did you know about US unemployment rules before she told you? What did you do with that afterwards?', 'What do you think now about offering people the chance to resign?', 'Which painting was it?'],
  }),
  S({
    id: 'S009', sourceRef: 'Cartography #12 "When experience becomes a burden"',
    title: 'Mentoring someone into a job I could see would go wrong',
    period: '“Last year” (relative to the source)', people: 'Someone I mentored, preparing for a job interview',
    happening: 'As I listened to their experience with the hiring process, red flags jumped out: dodgy comments about the team, unclear budgets, and conflicting priorities. This wasn’t a business I’d want to work for — too many things I’d seen before, and they’d never ended well.',
    difficulty: 'How do you share your experience without crushing someone’s excitement?',
    did: 'I chose to be honest, balancing my concerns with encouragement.',
    next: 'They appreciated the warning, but let the hope of the situation win. I hoped I was wrong.',
    outcome: 'In the end, I was disappointed to be right.',
    thinkNow: 'It’s a strange burden to see patterns others don’t — part sadness for what’s likely ahead, part relief at being able to help. Sometimes, experience is a gift but other times, it’s a pain in the arse.',
    ideas: 'Pattern recognition as the adviser’s asset and burden. Unclear budgets and conflicting priorities as tells that a business decision is unresolved.',
    territories: ['P', 'H'], relatedQuestions: [76, 13, 75],
    followups: ['What exactly were the “dodgy comments about the team”?', 'What went wrong, and how quickly?', 'Would you say it more bluntly next time?'],
  }),
  S({
    id: 'S010', sourceRef: 'Cartography #13 "Spotting what other people are going to do"',
    title: 'Telling her she wasn’t going to take the job',
    people: 'A friend/mentee weighing a job offer',
    happening: 'I knew she wasn’t going to take the job. We’d spent an hour discussing it, but her answers told a different story. “I don’t think you’re going to take it,” I said. “Everything you’ve said points the other way.” She seemed surprised. “Really? I think I might.”',
    outcome: 'Two days later, she declined the offer. Instead, I helped her negotiate for more money in her current role.',
    thinkNow: 'This ability to predict decisions and directions — whether for people or businesses — comes from asking the right questions and following intuition. It’s hard to explain, harder to teach, but it’s a skill I rely on.',
    ideas: 'Questions as the adviser’s method. The same skill applied to businesses: spotting trends, knowing who will thrive in a role.',
    territories: ['P', 'J'], relatedQuestions: [59, 76, 80],
    followups: ['What were the questions you asked that told you? Can you remember two?', 'How did you help with the negotiation — what was the leverage?', 'Where has the same instinct told you what a business would do?'],
  }),
  S({
    id: 'S011', sourceRef: 'Cartography #15 "The Weakness in Aggressive Negotiation"',
    title: 'My CEO’s way of negotiating, and the software implementation it soured',
    people: 'My CEO; a software supplier', context: 'A software implementation I was involved in',
    happening: 'I hate the way they negotiate — aggressive, domineering, and ultimately weak. My CEO believes success means leaving the other party with nothing, while I believe it’s about creating an outcome where both sides are satisfied. I’ve seen what happens when someone is squeezed on price, like during a software implementation I was involved in. The result? A strained relationship, poor value, and a subpar outcome. I hated every minute of it.',
    thinkNow: 'If we hadn’t been so focused on parading dominance, we could have relaxed, addressed the real issues, and worked together to solve them. Negotiation shouldn’t be a battle — it should be the foundation of a productive partnership. Some people have to feel like they’re always winning; I guess I’m not one of them.',
    ideas: 'Ego interfering with the commercial decision. Disagreeing with the CEO’s method while executing inside it.',
    territories: ['J', 'L', 'D'], relatedQuestions: [40, 47, 71],
    followups: ['Which implementation, roughly when?', 'Did you say any of this to the CEO? What happened?', 'What did “subpar outcome” actually look like — what did the business lose?'],
  }),
  S({
    id: 'S012', sourceRef: 'Cartography #16 "Endorsing the rules as a rule breaker"',
    title: 'Distributing a 3% pay pot as fairly as I could',
    context: 'My company gives a pot of 3% for increases pooled across each team — performance raises, inflation, the lot.',
    role: 'Deciding who gets what within the pot.',
    happening: 'For some people, 3% of the pot is 10% of their salary. For others, it barely makes a scratch. Everyone starts with 3% of their own salary. Then I start chiselling — new starters don’t get any, people who aren’t performing at the stronger end, they go too. And then we’re left with an extra pot to distribute against high performers and those with a gap against market rate.',
    difficulty: 'It’s hard, and everyone is angry.',
    thoughtThen: 'All I can do is be as fair as possible, even if it makes me the bad guy. And then pray that we all make it through until next time.',
    ideas: 'Endorsing a rule you’d break. Decisions about people you personally care about, inside constraints you didn’t set.',
    territories: ['D', 'E', 'C'], relatedQuestions: [43, 40, 50],
    followups: ['What was the market-rate gap you were trying to close, and for whom?', 'Did anyone leave over it?', 'What would you change about the rule if you could?'],
  }),
  S({
    id: 'S013', sourceRef: 'Cartography #18, #19, #22 (the budget)',
    title: 'The budget I couldn’t make myself finish — and then made work',
    context: 'A budget, at a point where the expectation had changed and I was being spoken to like a finance person.',
    happening: 'I couldn’t get the numbers to work. I knew what had been spent, but what I was expecting wasn’t what was staring back at me. I felt locked in my own head. The numbers had swamped me, I’d always been able to wrangle them before, but at this point I just couldn’t get myself to focus. I didn’t care. And that was the first time I’ve met a struggle like this with apathy.',
    difficulty: 'I was good at numbers for a creative, but somewhere along the process the expectation had changed and I was being spoken to like a finance person. I wanted to do well, even when I was hating it.',
    outcome: 'I got off the call and felt a sense of energy, and achievement “I DID IT.” I made those numbers work. I felt excitement over the thing that just a day earlier I was inconsolable over.',
    thoughtThen: '“This wasn’t how it was meant to go.” Sad that it felt out of control but pleased that finally, I was struggling to give full attention to something I didn’t care about. This might be the start of something new.',
    thinkNow: 'Clearly not the type of person who was only good at the things they enjoyed, I had become my own sacrifice. Angles noted in the source: overthinking, creatives doing numbers, numbers for non-finance.',
    ideas: 'Being expected to understand finance/budgets as seniority increased. Functional seniority creating responsibilities outside the function.',
    territories: ['F', 'K', 'S', 'M'], relatedQuestions: [16, 45, 70],
    followups: ['What had changed in the expectation — a new CFO, a new CEO, a bigger remit?', 'What did you not understand that a finance person would have? What did you understand that they didn’t?', 'Who was on the call at the end, and what made the numbers work?'],
  }),
  S({
    id: 'S014', sourceRef: 'Cartography #23 "Going to Workaholics anonymous"',
    title: 'Workaholics Anonymous at 26',
    period: 'Age 26; 80-hour weeks for years',
    happening: 'My identity was completely tied to work — I was the young marketing prodigy, the one who would outwork anyone. It was just me and two Asian lawyers. They were there because they didn’t know how to do anything else. I was there because I didn’t want to do anything else.',
    thoughtThen: 'I loved work. I hated how much I loved it. It gave me everything, and it took everything from me. Fulfilled yet deeply unsatisfied. I wasn’t ready to change my identity or face the parts of life I’d avoided. I remember wondering if I were a psychopath as they read the serenity prayer.',
    thinkNow: 'If I were to stop defining myself by role, I’d need a new identity first.',
    ideas: 'Professional identity tied to seniority and work. What happens to a person when the role is the identity.',
    territories: ['K'], relatedQuestions: [14],
    followups: ['What was the job at 26, and what was the “unravelling life” around it?', 'Has the identity ever come loose from the role since — when?'],
  }),
  S({
    id: 'S015', sourceRef: 'Cartography #21, #42, #67 (pregnancy and returning to work)',
    title: 'Hiding a pregnancy, and deciding whether to go back',
    happening: 'Every person I told was shocked. Two people were silenced, lost for words, a few thought it was a joke. One person laughed. My identity was someone who loved to work. I did long hours and loved nothing more than a trip overseas.',
    difficulty: 'Getting pregnant and addressing this change made me go into myself, to work out how to handle such a mess of emotion. How to survive a reincarnation or sacrifice of my identity. And that’s why I was dreading telling people. Later: torn between spending more time with my daughter, starting a business, or returning to corporate life for a safer, easier transition back to my old identity.',
    did: 'Ultimately, I chose the latter. At first, I convinced myself I’d just work long enough to sort out the maternity payments. I told myself it would only be for three to six months.',
    outcome: 'But here I am, still in the same job, caught in a cycle of knowing I need to leave but feeling scared of what comes next.',
    thinkNow: 'Looking back, I still wrestle with whether it was the right choice. It provided stability, but it also made making changes later much harder. Bold decisions were easier in my 20s.',
    ideas: 'Professional identity when the person changes rather than the company. Security vs. change; the cost of the “safer” transition.',
    territories: ['K', 'Q'], relatedQuestions: [14, 47],
    followups: ['Who laughed, and what did that tell you about how people saw you?', 'What did “the old identity” give you on return that you expected — and what didn’t come back?'],
  }),
  S({
    id: 'S016', sourceRef: 'Cartography #26, #53 (selling the house, moving to Paris)',
    title: 'Selling the house against advice and moving to Paris',
    period: 'February 2022', context: 'Brighton: 12 years in the town, 8 years in the job',
    happening: 'I was stuck and I needed out. I’d planned to be in Brighton for a year after graduation, planned to be at the job for a couple of years at best. But there I was, 12 years in the town and 8 years in the job and it’d gone on for too long. I had to burn the boats. Despite everyone advising me not to sell without a plan or a new property lined up, I knew deep down it was the right move.',
    did: 'I put the house up for sale and arranged to live in Paris for a while. And after that? No idea.',
    thoughtThen: '“Why don’t you just go to Paris for the summer?” people would ask. It was tempting and safe. And that’s the reason why I had to cut and run before I spent another decade there. I had to take that dramatic step to release what no longer served me, or I’d always find a way back.',
    outcome: 'For the first time in a long time, I felt excitement.',
    ideas: 'Accepted advice not fitting; knowing when to make an irreversible move so the safe option can’t win. Preserve vs. leave behind — for a person, not a company.',
    territories: ['Q', 'M', 'K'], relatedQuestions: [4, 47],
    followups: ['Which job was it, and what had kept you 8 years?', 'What did the people advising you actually fear, and were they partly right?'],
  }),
  S({
    id: 'S017', sourceRef: 'Cartography #34 "I didn’t want to take the job"',
    title: 'Taking the job “temporarily”, then being paid less than advertised',
    people: 'My boss',
    happening: 'My boss said that I should, “you can do it temporarily” he said. But somewhere between that and doing it, I started to feel that I wanted it. I knew what I was doing; the job was mine. I was offered less money than was advertised — I had less experience they said.',
    thoughtThen: 'I accepted it as a learning opportunity but I felt short changed.',
    ideas: 'Promotion into a role without the confidence to make the case; authority before confidence. Being underpaid for a job you are already doing.',
    territories: ['K', 'N', 'J'], relatedQuestions: [45, 12],
    followups: ['Which job was this — the step up to running the team?', 'What would you have said in that salary conversation now?', 'Did you ever close the gap?'],
  }),
  S({
    id: 'S018', sourceRef: 'Cartography #50, #51 (Dr Mark Britton event)',
    title: 'Discovering there was a name for “growth campaigns”',
    period: '2024', context: 'A marketing event hosted by Dr. Mark Britton',
    happening: 'He explained a structured approach to campaigns: a long-term brand campaign running continuously, layered with short, targeted bursts for specific products or offers. This was exactly how I’d been working for years, without ever being formally taught. I called them “growth campaigns,” and I had built templates and processes around it, purely from instinct and observation as a customer.',
    thoughtThen: 'Hearing it articulated wasn’t just validating — it showed me that my gut-driven approach wasn’t just practical; it was a recognized industry technique.',
    thinkNow: 'Sometimes, the best strategies aren’t learned from books — they’re born from intuition, observation, and what simply makes sense.',
    ideas: 'Discovering formal names for strategies developed intuitively. How judgement is actually developed vs. how it is taught. (Contradiction worth holding: S005 says the taught version was wrong; here the taught version matched.)',
    territories: ['F', 'G', 'Q'], relatedQuestions: [58, 54],
    followups: ['Did having the name change anything about how you argued for the approach afterwards?', 'What did you build the templates from — which company, which products?'],
  }),
  S({
    id: 'S019', sourceRef: 'Cartography #60, #64, #65 (feedback from people I’ve managed; creative leadership)',
    title: 'Asking people I’ve managed for feedback — “more interest in the creative side than any non-design manager”',
    period: 'During the Personal Cartography exercise', people: 'An art director I’ve worked with for six years; Ben',
    happening: 'I reached out to people I’ve managed over the years to ask for feedback. It was nerve-wracking. “Why is she asking for something positive?” One of the most striking pieces came from an art director: he said I had more interest in the creative and artistic side of what design teams do than any other non-design manager he’d worked with. Ben mentioned how much I light up during design-related conversations.',
    thinkNow: 'Brilliant ideas often need a bridge to become commercially viable. I’ve developed a knack for identifying the core DNA of a creative business — who they are, what they produce, and how they can make it work commercially without losing their essence. Originally, I planned to go to art school, but I ended up in marketing at a listed company instead.',
    ideas: 'Bridging creative and commercial thinking as a defining trait. Rebrands where engaging with the creative work made the difference.',
    territories: ['O', 'I', 'R'], relatedQuestions: [9, 8],
    followups: ['Which rebrand is the best example — what did “engaging deeply with the creative work” change in the outcome?', 'When did the commercial side flatten a creative idea, and what did you do?', 'When was the creative idea good but commercially wrong?'],
  }),
  S({
    id: 'S020', sourceRef: 'Cartography, later items: "Helping Harrison"; "Person 1"; "Person 2"; #72, #73',
    title: 'People coming to me to work out what they’re good at',
    people: 'Harrison; Person 1; Person 2 (unnamed)',
    happening: '“When I speak with you, you shunt my life forwards in the right direction” is what he said. I’ve been helping him to work out what he’s great at; where his skills are unique within the market, how he can package and sell his skills within an offer. I helped Person 1 assess how their skills could be used during a point of big transition — a workshop, then notes; they said it was “transformative” and “a premium service”. I helped Person 2 identify the key stories and experiences they could call out during the job interview process; we mapped out the proof for the things they’d done and wrapped it up in value statements.',
    thinkNow: 'I’ve found I’m at my best when I do this informally. There’s an authenticity in those casual settings that’s harder to replicate in formal ones. When it comes to formalising that work or charging for it, something shifts — the passion feels harder to sustain.',
    quotes: '“When I speak with you, you shunt my life forwards in the right direction.”',
    ideas: 'The informal adviser role: connecting someone’s dots; the tension between informal authenticity and a paid, defined service. (Source also lists: “Good at spotting what people are good at (eg: GTM discussion with Harrison)”.)',
    territories: ['P', 'J'], relatedQuestions: [74, 76, 78],
    followups: ['What was the GTM discussion with Harrison — what did you see that he couldn’t?', 'What was Person 1’s transition, and what were the recommendations?', 'When have you told someone they needed someone else instead of you?'],
  }),
  S({
    id: 'S021', kind: 'lead', sourceRef: 'Cartography, later items: "Good at understanding what the masses think and raising it to senior leaders (eg: bonus deal)"',
    title: 'The bonus deal: raising what the masses think to senior leaders',
    happening: 'Only a one-line note in the source: “Good at understanding what the masses think and raising it to senior leaders (eg: bonus deal).”',
    ideas: 'Translating between the organisation and the leadership; being on the leader’s side of the table while still challenging them.',
    territories: ['L', 'D', 'P'], relatedQuestions: [75, 42],
    followups: ['What was the bonus deal — what was leadership proposing and what did people actually think?', 'How did you raise it, to whom, and what happened?', 'What did it cost you to be the one who said it?'],
  }),
  S({
    id: 'S022', kind: 'lead', sourceRef: 'Cartography #70 "The person who believed I was ready"',
    title: 'The first boss who took a chance on me',
    people: 'My first boss (at LTG, per #71)',
    happening: 'My first boss took a chance on me, he saw that I could lead a team even when I thought it was early. He would wear Vans slip on trainers when everyone else wore suits. He was flamboyant, bold and opinionated. He supported me being who I was, joking about my wearing black and pushing me to do well.',
    ideas: 'Being promoted before you can make your own case. One person who backed her.',
    territories: ['R', 'N', 'C'], relatedQuestions: [11, 45],
    followups: ['What was the moment he decided — what did he say?', 'What did he see that you couldn’t? Were you actually ready?', 'What did you get wrong in that first year of leading?'],
  }),
  S({
    id: 'S023', kind: 'lead', sourceRef: 'Cartography #71 "The person who advocated for my MBA sponsorship"',
    title: 'The L&D lead who got my MBA funded',
    people: 'The L&D lady; the CEO; my first boss at LTG',
    happening: 'She went out of her way to support me, to pitch the case to get my MBA funded so that I could do one without the fee or needing to stop working. She made the argument to the CEO, she pitched in the funding, she helped me meet deadlines. It was her and my first boss at LTG that gave me the courage to believe that I could work in corporate and that I could be and do more than I thought.',
    ideas: 'Develop vs. hire, from the inside: what it took for a company to invest in someone.',
    territories: ['R', 'C'], relatedQuestions: [11],
    followups: ['What was the case she made to the CEO — why you, why then?', 'What did the company get back, and did it keep you longer?'],
  }),
  S({
    id: 'S024', kind: 'lead', sourceRef: 'Cartography #28; "Buying courses to avoid the doing"; later item "Buying business courses… ending up becoming the advisor"',
    title: 'Paying experts I ended up teaching',
    happening: 'I’ve paid experts that I’ve ended up teaching, joined business courses run by people with less experience than me. I used to buy countless courses, thinking each one held the missing piece. Looking back, I see that it was less about learning and more about avoiding action.',
    thinkNow: 'Readiness doesn’t come from consuming more — it comes from starting, but it’s hard. The people around me doing well aren’t better, they’re just able to stick with it.',
    ideas: 'Becoming the adviser while looking for advice. When a competent-sounding expert knows less than the client. Knowing when another specialist is needed — or isn’t.',
    territories: ['P', 'G', 'Q'], relatedQuestions: [56, 79, 78],
    followups: ['Which course, which expert — what were you hoping they had?', 'At what point in the room did you realise you knew more? What did you do?'],
  }),
  S({
    id: 'S025', kind: 'lead', sourceRef: 'Cartography #57 "My first panic attack"',
    title: 'Paralysed at Victoria station, between home and an office where I was the outsider',
    happening: 'I was paralysed in London’s Victoria station trying to get to work. Stuck in the intersection between the routes to the office and back home. Too loud to reason. I was stuck between a home I wasn’t comfortable in and going to an office where I was made to feel like an outsider.',
    ideas: 'Absorbing pressure from two directions; what pressure does to judgement. Which office, and why an outsider there? (The source does not say.)',
    territories: ['D', 'M', 'E'], relatedQuestions: [52, 48],
    followups: ['Which office was this, and what made you the outsider there?', 'What did you do that day, and the next?', 'Did anyone at work know?'],
  }),
  S({
    id: 'S026', kind: 'lead', sourceRef: 'Cartography, closing list: "Making people redundant"; "The messiness of my own beliefs against a corporation"; "Pride to keep my own unique style throughout hard times"',
    title: 'Making people redundant (the deals behind S002 and S005)',
    happening: 'Listed in the source as territory still to write: making people redundant; the messiness of my own beliefs against a corporation; pride at keeping my own unique style throughout hard times.',
    territories: ['E', 'D', 'B', 'Q'], relatedQuestions: [50, 43, 40],
    followups: ['Pick one redundancy round. Where, when, how many people, and whose decision?', 'What did you know that the team didn’t, and what couldn’t you tell them?', 'Where did your beliefs and the corporation’s collide — what did you do?'],
  }),
  S({
    id: 'S027', kind: 'lead', sourceRef: 'Cartography #74 "Home is a dive bar in an alien city"; #63 "Mastering New Skills Fast"',
    title: 'Learning to talk to anyone, travelling the States between deals',
    happening: 'Travelling all around the states, meeting people and learning to talk to anyone. Separately: when I get interested in something, I dive in deep — a friend pointed out how I went from not knowing what a deadlift was to knowing more about weightlifting than some personal trainers in a year.',
    ideas: 'Fast learning as the method for working outside expertise. Nashville, Raleigh (“been to 6 times in the last year”), Atlanta, Tennessee appear in the source — the geography of the deals.',
    territories: ['F', 'B'], relatedQuestions: [16, 58],
    followups: ['Which businesses were in Raleigh, Nashville, Atlanta, Tennessee? What was each visit for?', 'What was the fastest you had to learn something for a deal — what was it?'],
  }),
];

// Territories (§16) the document names but which do not yet have a record of their own.
export const STORY_LEADS_NOTE = 'Not imported from Personal Cartography (personal, family or health items outside the thesis): #2–4, #8, #10, #14, #17, #20, #24, #25, #27, #29, #30, #32, #33, #35–39, #40, #43–49, #52, #54–56, #58, #59, #61, #62, #66, #71, “Handling intense emotions”, “Feeling resentful of longer commitments”. Add any of them from the document if you want them in the bank.';
